apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: java-deployment 
spec: 
  selector: 
    matchLabels: 
      app: java 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: java 
    spec: 
      containers: 
      - name: java 
        image: autodeploy.azurecr.io/csandhya8/springbootmavenjunitsample:#{Release.Artifacts._Auto-Deploy-Docker container-CI.BuildId}#
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: autodeploy      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-service 
spec: 
  selector: 
    app: java 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: helloworld-deployment 
spec: 
  selector: 
    matchLabels: 
      app: helloworld 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: helloworld
    spec: 
      containers: 
      - name: helloworld
        image: autodeploy.azurecr.io/csandhya8/spring-boot-maven-example-helloworld:#{Release.Artifacts._autodeploy2.BuildId}#
        ports: 
        - containerPort: 8081
      imagePullSecrets:
      - name: autodeploy     
---
kind: Service 
apiVersion: v1 
metadata: 
  name: helloworld-service 
spec: 
  selector: 
    app: helloworld 
  ports: 
  - protocol: TCP 
    port: 8081 
    targetPort: 8081 
  type: LoadBalancer 
